name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
    types: [checks_requested]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build with Maven
        run: ./mvnw --batch-mode --no-transfer-progress verify
      - name: Upload generated-docs
        uses: actions/upload-artifact@v4
        with:
          name: generated-docs
          path: docs/target/generated-docs/*
          retention-days: 7
